{
  "openapi": "3.0.1",
  "info": {
    "title": "ProxyKingdom-Api",
    "version": "v1",
    "x-jentic-source-url": "https://api.proxykingdom.com/swagger/v1/swagger.json"
  },
  "servers": [
    {
      "url": "https://api.proxykingdom.com"
    }
  ],
  "paths": {
    "/proxy": {
      "get": {
        "tags": [
          "Proxy"
        ],
        "summary": "Gets a random proxy for chosen parameters.",
        "parameters": [
          {
            "name": "Token",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Address",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Port",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Protocol",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "AccessType",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "ResponseTime",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "IsSsl",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Uptime",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Country",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Continent",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Timezone",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "LastTested",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "correlation_id",
            "in": "header",
            "description": "Correlation Id header field",
            "required": true,
            "schema": {
              "type": "string",
              "default": "c7e27445-6d39-4431-9de4-236cb552e92d"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/Proxy"
                },
                "example": {
                  "address": "86.125.112.230",
                  "port": 30897,
                  "protocol": "Socks4",
                  "accessType": "Elite",
                  "isSsl": true,
                  "uptime": 0.88,
                  "timings": {
                    "connectTime": 0.506,
                    "firstByteTime": 0.607,
                    "responseTime": 1.092
                  },
                  "isp": {
                    "id": 10232,
                    "name": "Comcast"
                  },
                  "location": {
                    "cityName": "Timi\u0219oara",
                    "postalCode": "300011",
                    "latitude": 45.7537,
                    "longitude": 21.7537,
                    "accuracyRadius": 1,
                    "timezone": "Europe/Bucharest",
                    "country": {
                      "code": "RO",
                      "name": "Romania"
                    },
                    "continent": {
                      "code": "EU",
                      "name": "Europe"
                    },
                    "subdivisions": [
                      {
                        "code": "TM",
                        "name": "Timis"
                      }
                    ]
                  },
                  "lastTested": "2025-03-31T17:56:52Z"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Proxy"
                },
                "example": {
                  "address": "86.125.112.230",
                  "port": 30897,
                  "protocol": "Socks4",
                  "accessType": "Elite",
                  "isSsl": true,
                  "uptime": 0.88,
                  "timings": {
                    "connectTime": 0.506,
                    "firstByteTime": 0.607,
                    "responseTime": 1.092
                  },
                  "isp": {
                    "id": 10232,
                    "name": "Comcast"
                  },
                  "location": {
                    "cityName": "Timi\u0219oara",
                    "postalCode": "300011",
                    "latitude": 45.7537,
                    "longitude": 21.7537,
                    "accuracyRadius": 1,
                    "timezone": "Europe/Bucharest",
                    "country": {
                      "code": "RO",
                      "name": "Romania"
                    },
                    "continent": {
                      "code": "EU",
                      "name": "Europe"
                    },
                    "subdivisions": [
                      {
                        "code": "TM",
                        "name": "Timis"
                      }
                    ]
                  },
                  "lastTested": "2025-03-31T17:56:52Z"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/Proxy"
                },
                "example": {
                  "address": "86.125.112.230",
                  "port": 30897,
                  "protocol": "Socks4",
                  "accessType": "Elite",
                  "isSsl": true,
                  "uptime": 0.88,
                  "timings": {
                    "connectTime": 0.506,
                    "firstByteTime": 0.607,
                    "responseTime": 1.092
                  },
                  "isp": {
                    "id": 10232,
                    "name": "Comcast"
                  },
                  "location": {
                    "cityName": "Timi\u0219oara",
                    "postalCode": "300011",
                    "latitude": 45.7537,
                    "longitude": 21.7537,
                    "accuracyRadius": 1,
                    "timezone": "Europe/Bucharest",
                    "country": {
                      "code": "RO",
                      "name": "Romania"
                    },
                    "continent": {
                      "code": "EU",
                      "name": "Europe"
                    },
                    "subdivisions": [
                      {
                        "code": "TM",
                        "name": "Timis"
                      }
                    ]
                  },
                  "lastTested": "2025-03-31T17:56:52Z"
                }
              }
            }
          },
          "400": {
            "description": "Invalid proxy filter provided."
          },
          "404": {
            "description": "No Proxy found for GetProxy by filter."
          },
          "429": {
            "description": "Subscription limit reached."
          },
          "500": {
            "description": "Technical Error."
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Continent": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string",
            "nullable": true,
            "readOnly": true
          },
          "name": {
            "type": "string",
            "nullable": true,
            "readOnly": true
          }
        },
        "additionalProperties": false
      },
      "Country": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string",
            "nullable": true,
            "readOnly": true
          },
          "name": {
            "type": "string",
            "nullable": true,
            "readOnly": true
          }
        },
        "additionalProperties": false
      },
      "Isp": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32",
            "readOnly": true
          },
          "name": {
            "type": "string",
            "nullable": true,
            "readOnly": true
          }
        },
        "additionalProperties": false
      },
      "Location": {
        "type": "object",
        "properties": {
          "cityName": {
            "type": "string",
            "nullable": true,
            "readOnly": true
          },
          "postalCode": {
            "type": "string",
            "nullable": true,
            "readOnly": true
          },
          "latitude": {
            "type": "number",
            "format": "float",
            "readOnly": true
          },
          "longitude": {
            "type": "number",
            "format": "float",
            "readOnly": true
          },
          "accuracyRadius": {
            "type": "integer",
            "format": "int32",
            "readOnly": true
          },
          "timezone": {
            "type": "string",
            "nullable": true,
            "readOnly": true
          },
          "country": {
            "$ref": "#/components/schemas/Country"
          },
          "continent": {
            "$ref": "#/components/schemas/Continent"
          },
          "subdivisions": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Subdivision"
            },
            "nullable": true,
            "readOnly": true
          }
        },
        "additionalProperties": false
      },
      "Proxy": {
        "type": "object",
        "properties": {
          "address": {
            "type": "string",
            "nullable": true,
            "readOnly": true
          },
          "port": {
            "type": "integer",
            "format": "int32",
            "readOnly": true
          },
          "protocol": {
            "type": "string",
            "nullable": true,
            "readOnly": true
          },
          "accessType": {
            "type": "string",
            "nullable": true,
            "readOnly": true
          },
          "isSsl": {
            "type": "boolean",
            "readOnly": true
          },
          "uptime": {
            "type": "number",
            "format": "float",
            "readOnly": true
          },
          "timings": {
            "$ref": "#/components/schemas/Timings"
          },
          "isp": {
            "$ref": "#/components/schemas/Isp"
          },
          "location": {
            "$ref": "#/components/schemas/Location"
          },
          "lastTested": {
            "type": "string",
            "nullable": true,
            "readOnly": true
          }
        },
        "additionalProperties": false
      },
      "Subdivision": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string",
            "nullable": true,
            "readOnly": true
          },
          "name": {
            "type": "string",
            "nullable": true,
            "readOnly": true
          }
        },
        "additionalProperties": false
      },
      "Timings": {
        "type": "object",
        "properties": {
          "connectTime": {
            "type": "number",
            "format": "float",
            "readOnly": true
          },
          "firstByteTime": {
            "type": "number",
            "format": "float",
            "readOnly": true
          },
          "responseTime": {
            "type": "number",
            "format": "float",
            "readOnly": true
          }
        },
        "additionalProperties": false
      }
    }
  },
  "externalDocs": {
    "description": "ProxyKingdom's Documentation",
    "url": "https://proxykingdom.com/documentation"
  }
}