{
  "openapi": "3.0.0",
  "info": {
    "title": "PolicyTrackedResourcesClient",
    "version": "2018-07-01-preview",
    "x-apisguru-categories": [
      "cloud"
    ],
    "x-jentic-source-url": "https://api.apis.guru/v2/specs/azure.com/policyinsights-policyTrackedResources/2018-07-01-preview/swagger.yaml",
    "x-logo": {
      "url": "https://api.apis.guru/v2/cache/logo/https_assets.onestore.ms_cdnfiles_onestorerolling-1606-01000_shell_v3_images_logo_microsoft.png"
    },
    "x-origin": [
      {
        "format": "swagger",
        "url": "https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/policyinsights/resource-manager/Microsoft.PolicyInsights/preview/2018-07-01-preview/policyTrackedResources.json",
        "version": "2.0"
      }
    ],
    "x-providerName": "azure.com",
    "x-serviceName": "policyinsights-policyTrackedResources",
    "x-tags": [
      "Azure",
      "Microsoft"
    ],
    "description": "PolicyTrackedResourcesClient provides programmatic access to providers, subscriptions resources."
  },
  "servers": [
    {
      "url": "https://management.azure.com/"
    }
  ],
  "paths": {
    "/providers/{managementGroupsNamespace}/managementGroups/{managementGroupName}/providers/Microsoft.PolicyInsights/policyTrackedResources/{policyTrackedResourcesResource}/queryResults": {
      "post": {
        "parameters": [
          {
            "$ref": "#/components/parameters/managementGroupsNamespaceParameter"
          },
          {
            "$ref": "#/components/parameters/managementGroupNameParameter"
          },
          {
            "$ref": "#/components/parameters/policyTrackedResourcesResourceParameter"
          },
          {
            "$ref": "#/components/parameters/topParameter"
          },
          {
            "$ref": "#/components/parameters/filterParameter"
          },
          {
            "$ref": "#/components/parameters/apiVersionParameter"
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PolicyTrackedResourcesQueryResults"
                }
              }
            },
            "description": "Query results."
          },
          "default": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/QueryFailure"
                }
              }
            },
            "description": "Error response describing why the operation failed."
          }
        },
        "description": "Queries policy tracked resources under the management group.",
        "operationId": "PolicyTrackedResources_ListQueryResultsForManagementGroup",
        "x-ms-examples": {
          "Query at management group scope": {
            "parameters": {
              "api-version": "2018-07-01-preview",
              "managementGroupName": "myManagementGroup",
              "managementGroupsNamespace": "Microsoft.Management",
              "policyTrackedResourcesResource": "default"
            },
            "responses": {
              "200": {
                "body": {
                  "value": [
                    {
                      "createdBy": {
                        "deploymentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Resources/deployments/deploymentName",
                        "deploymentTime": "2018-03-09 00:00:00+00:00",
                        "policyDetails": {
                          "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/createdByPolicyAssignment",
                          "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/",
                          "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/createdByPolicyDefinition"
                        }
                      },
                      "lastModifiedBy": {
                        "deploymentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Resources/deployments/deploymentName",
                        "deploymentTime": "2018-04-09 00:00:00+00:00",
                        "policyDetails": {
                          "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/lastModifiedByPolicyAssignment",
                          "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/",
                          "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/lastModifiedByPolicyDefinition"
                        }
                      },
                      "lastUpdateUtc": "2018-08-09 20:40:17.358524+00:00",
                      "policyDetails": {
                        "policyAssignmentDisplayName": "My Policy Assignment 1 Display name",
                        "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/myPolicyAssignment1",
                        "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/",
                        "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/myPolicyDefinition1",
                        "policyDefinitionReferenceId": "123ABC",
                        "policySetDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/providers/Microsoft.Authorization/policySetDefinitions/mySetDefinition"
                      },
                      "trackedResourceId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Example/exampleResourceType/exampleTrackedResourceName1"
                    },
                    {
                      "lastUpdateUtc": "2018-08-10 00:40:17.358524+00:00",
                      "policyDetails": {
                        "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/providers/Microsoft.Authorization/policyAssignments/myPolicyAssignment2",
                        "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/",
                        "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/myPolicyDefinition2"
                      },
                      "trackedResourceId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Example/exampleResourceType/exampleTrackedResourceName2"
                    }
                  ]
                }
              }
            }
          },
          "Query at management group scope using query parameters": {
            "parameters": {
              "$filter": "PolicyAssignmentId eq '/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/myPolicyAssignment' AND TrackedResourceId eq '/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Example/exampleResourceType/exampleTrackedResourceName'",
              "$top": 1,
              "api-version": "2018-07-01-preview",
              "managementGroupName": "myManagementGroup",
              "managementGroupsNamespace": "Microsoft.Management",
              "policyTrackedResourcesResource": "default"
            },
            "responses": {
              "200": {
                "body": {
                  "value": [
                    {
                      "createdBy": {
                        "deploymentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Resources/deployments/deploymentName",
                        "deploymentTime": "2018-03-09 00:00:00+00:00",
                        "policyDetails": {
                          "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/createdByPolicyAssignment",
                          "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/",
                          "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/createdByPolicyDefinition"
                        }
                      },
                      "lastModifiedBy": {
                        "deploymentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Resources/deployments/deploymentName",
                        "deploymentTime": "2018-04-09 00:00:00+00:00",
                        "policyDetails": {
                          "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/lastModifiedByPolicyAssignment",
                          "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/",
                          "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/lastModifiedByPolicyDefinition"
                        }
                      },
                      "lastUpdateUtc": "2018-08-09 20:40:17.358524+00:00",
                      "policyDetails": {
                        "policyAssignmentDisplayName": "My Policy Assignment Display name",
                        "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/myPolicyAssignment",
                        "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/",
                        "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/myPolicyDefinition",
                        "policyDefinitionReferenceId": "123ABC",
                        "policySetDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/providers/Microsoft.Authorization/policySetDefinitions/mySetDefinition"
                      },
                      "trackedResourceId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Example/exampleResourceType/exampleTrackedResourceName"
                    }
                  ]
                }
              }
            }
          }
        },
        "x-ms-pageable": {
          "nextLinkName": "nextLink"
        }
      }
    },
    "/subscriptions/{subscriptionId}/providers/Microsoft.PolicyInsights/policyTrackedResources/{policyTrackedResourcesResource}/queryResults": {
      "post": {
        "parameters": [
          {
            "$ref": "#/components/parameters/policyTrackedResourcesResourceParameter"
          },
          {
            "$ref": "#/components/parameters/topParameter"
          },
          {
            "$ref": "#/components/parameters/filterParameter"
          },
          {
            "$ref": "#/components/parameters/subscriptionIdParameter"
          },
          {
            "$ref": "#/components/parameters/apiVersionParameter"
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PolicyTrackedResourcesQueryResults"
                }
              }
            },
            "description": "Query results."
          },
          "default": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/QueryFailure"
                }
              }
            },
            "description": "Error response describing why the operation failed."
          }
        },
        "description": "Queries policy tracked resources under the subscription.",
        "operationId": "PolicyTrackedResources_ListQueryResultsForSubscription",
        "x-ms-examples": {
          "Query at subscription scope": {
            "parameters": {
              "api-version": "2018-07-01-preview",
              "policyTrackedResourcesResource": "default",
              "subscriptionId": "fffedd8f-ffff-fffd-fffd-fffed2f84852"
            },
            "responses": {
              "200": {
                "body": {
                  "value": [
                    {
                      "createdBy": {
                        "deploymentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Resources/deployments/deploymentName",
                        "deploymentTime": "2018-03-09 00:00:00+00:00",
                        "policyDetails": {
                          "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/createdByPolicyAssignment",
                          "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/",
                          "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/createdByPolicyDefinition"
                        }
                      },
                      "lastModifiedBy": {
                        "deploymentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Resources/deployments/deploymentName",
                        "deploymentTime": "2018-04-09 00:00:00+00:00",
                        "policyDetails": {
                          "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/lastModifiedByPolicyAssignment",
                          "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/",
                          "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/lastModifiedByPolicyDefinition"
                        }
                      },
                      "lastUpdateUtc": "2018-08-09 20:40:17.358524+00:00",
                      "policyDetails": {
                        "policyAssignmentDisplayName": "My Policy Assignment 1 Display name",
                        "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/myPolicyAssignment1",
                        "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/",
                        "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/myPolicyDefinition1",
                        "policyDefinitionReferenceId": "123ABC",
                        "policySetDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/providers/Microsoft.Authorization/policySetDefinitions/mySetDefinition"
                      },
                      "trackedResourceId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Example/exampleResourceType/exampleTrackedResourceName1"
                    },
                    {
                      "lastUpdateUtc": "2018-08-10 00:40:17.358524+00:00",
                      "policyDetails": {
                        "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/providers/Microsoft.Authorization/policyAssignments/myPolicyAssignment2",
                        "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/",
                        "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/myPolicyDefinition2"
                      },
                      "trackedResourceId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Example/exampleResourceType/exampleTrackedResourceName2"
                    }
                  ]
                }
              }
            }
          },
          "Query at subscription scope using query parameters": {
            "parameters": {
              "$filter": "PolicyAssignmentId eq '/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/myPolicyAssignment' AND TrackedResourceId eq '/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Example/exampleResourceType/exampleTrackedResourceName'",
              "$top": 1,
              "api-version": "2018-07-01-preview",
              "policyTrackedResourcesResource": "default",
              "subscriptionId": "fffedd8f-ffff-fffd-fffd-fffed2f84852"
            },
            "responses": {
              "200": {
                "body": {
                  "value": [
                    {
                      "createdBy": {
                        "deploymentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Resources/deployments/deploymentName",
                        "deploymentTime": "2018-03-09 00:00:00+00:00",
                        "policyDetails": {
                          "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/createdByPolicyAssignment",
                          "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/",
                          "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/createdByPolicyDefinition"
                        }
                      },
                      "lastModifiedBy": {
                        "deploymentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Resources/deployments/deploymentName",
                        "deploymentTime": "2018-04-09 00:00:00+00:00",
                        "policyDetails": {
                          "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/lastModifiedByPolicyAssignment",
                          "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/",
                          "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/lastModifiedByPolicyDefinition"
                        }
                      },
                      "lastUpdateUtc": "2018-08-09 20:40:17.358524+00:00",
                      "policyDetails": {
                        "policyAssignmentDisplayName": "My Policy Assignment Display name",
                        "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/myPolicyAssignment",
                        "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/",
                        "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/myPolicyDefinition",
                        "policyDefinitionReferenceId": "123ABC",
                        "policySetDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/providers/Microsoft.Authorization/policySetDefinitions/mySetDefinition"
                      },
                      "trackedResourceId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Example/exampleResourceType/exampleTrackedResourceName"
                    }
                  ]
                }
              }
            }
          }
        },
        "x-ms-pageable": {
          "nextLinkName": "nextLink"
        }
      }
    },
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.PolicyInsights/policyTrackedResources/{policyTrackedResourcesResource}/queryResults": {
      "post": {
        "parameters": [
          {
            "$ref": "#/components/parameters/resourceGroupNameParameter"
          },
          {
            "$ref": "#/components/parameters/policyTrackedResourcesResourceParameter"
          },
          {
            "$ref": "#/components/parameters/topParameter"
          },
          {
            "$ref": "#/components/parameters/filterParameter"
          },
          {
            "$ref": "#/components/parameters/subscriptionIdParameter"
          },
          {
            "$ref": "#/components/parameters/apiVersionParameter"
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PolicyTrackedResourcesQueryResults"
                }
              }
            },
            "description": "Query results."
          },
          "default": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/QueryFailure"
                }
              }
            },
            "description": "Error response describing why the operation failed."
          }
        },
        "description": "Queries policy tracked resources under the resource group.",
        "operationId": "PolicyTrackedResources_ListQueryResultsForResourceGroup",
        "x-ms-examples": {
          "Query at resource group scope": {
            "parameters": {
              "api-version": "2018-07-01-preview",
              "policyTrackedResourcesResource": "default",
              "resourceGroupName": "myResourceGroup",
              "subscriptionId": "fffedd8f-ffff-fffd-fffd-fffed2f84852"
            },
            "responses": {
              "200": {
                "body": {
                  "value": [
                    {
                      "createdBy": {
                        "deploymentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Resources/deployments/deploymentName",
                        "deploymentTime": "2018-03-09 00:00:00+00:00",
                        "policyDetails": {
                          "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/createdByPolicyAssignment",
                          "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/",
                          "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/createdByPolicyDefinition"
                        }
                      },
                      "lastModifiedBy": {
                        "deploymentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Resources/deployments/deploymentName",
                        "deploymentTime": "2018-04-09 00:00:00+00:00",
                        "policyDetails": {
                          "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/lastModifiedByPolicyAssignment",
                          "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/",
                          "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/lastModifiedByPolicyDefinition"
                        }
                      },
                      "lastUpdateUtc": "2018-08-09 20:40:17.358524+00:00",
                      "policyDetails": {
                        "policyAssignmentDisplayName": "My Policy Assignment 1 Display name",
                        "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/myPolicyAssignment1",
                        "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/",
                        "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/myPolicyDefinition1",
                        "policyDefinitionReferenceId": "123ABC",
                        "policySetDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/providers/Microsoft.Authorization/policySetDefinitions/mySetDefinition"
                      },
                      "trackedResourceId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Example/exampleResourceType/exampleTrackedResourceName1"
                    },
                    {
                      "lastUpdateUtc": "2018-08-10 00:40:17.358524+00:00",
                      "policyDetails": {
                        "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/providers/Microsoft.Authorization/policyAssignments/myPolicyAssignment2",
                        "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/",
                        "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/myPolicyDefinition2"
                      },
                      "trackedResourceId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Example/exampleResourceType/exampleTrackedResourceName2"
                    }
                  ]
                }
              }
            }
          },
          "Query at resource group scope using query parameters": {
            "parameters": {
              "$filter": "PolicyAssignmentId eq '/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/myPolicyAssignment' AND TrackedResourceId eq '/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Example/exampleResourceType/myResource/nestedResourceType/TrackedResource1'",
              "$top": 1,
              "api-version": "2018-07-01-preview",
              "policyTrackedResourcesResource": "default",
              "resourceGroupName": "myResourceGroup",
              "subscriptionId": "fffedd8f-ffff-fffd-fffd-fffed2f84852"
            },
            "responses": {
              "200": {
                "body": {
                  "value": [
                    {
                      "createdBy": {
                        "deploymentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Resources/deployments/deploymentName",
                        "deploymentTime": "2018-03-09 00:00:00+00:00",
                        "policyDetails": {
                          "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/createdByPolicyAssignment",
                          "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/",
                          "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/createdByPolicyDefinition"
                        }
                      },
                      "lastModifiedBy": {
                        "deploymentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Resources/deployments/deploymentName",
                        "deploymentTime": "2018-04-09 00:00:00+00:00",
                        "policyDetails": {
                          "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/lastModifiedByPolicyAssignment",
                          "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/",
                          "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/lastModifiedByPolicyDefinition"
                        }
                      },
                      "lastUpdateUtc": "2018-08-09 20:40:17.358524+00:00",
                      "policyDetails": {
                        "policyAssignmentDisplayName": "My Policy Assignment 1 Display name",
                        "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/myPolicyAssignment1",
                        "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/",
                        "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/myPolicyDefinition1",
                        "policyDefinitionReferenceId": "123ABC",
                        "policySetDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/providers/Microsoft.Authorization/policySetDefinitions/mySetDefinition"
                      },
                      "trackedResourceId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Example/exampleResourceType/myResource/nestedResourceType/TrackedResource1"
                    }
                  ]
                }
              }
            }
          }
        },
        "x-ms-pageable": {
          "nextLinkName": "nextLink"
        }
      }
    },
    "/{resourceId}/providers/Microsoft.PolicyInsights/policyTrackedResources/{policyTrackedResourcesResource}/queryResults": {
      "post": {
        "parameters": [
          {
            "$ref": "#/components/parameters/resourceIdParameter"
          },
          {
            "$ref": "#/components/parameters/policyTrackedResourcesResourceParameter"
          },
          {
            "$ref": "#/components/parameters/topParameter"
          },
          {
            "$ref": "#/components/parameters/filterParameter"
          },
          {
            "$ref": "#/components/parameters/apiVersionParameter"
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PolicyTrackedResourcesQueryResults"
                }
              }
            },
            "description": "Query results."
          },
          "default": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/QueryFailure"
                }
              }
            },
            "description": "Error response describing why the operation failed."
          }
        },
        "description": "Queries policy tracked resources under the resource.",
        "operationId": "PolicyTrackedResources_ListQueryResultsForResource",
        "x-ms-examples": {
          "Query at resource scope": {
            "parameters": {
              "api-version": "2018-07-01-preview",
              "policyTrackedResourcesResource": "default",
              "resourceId": "subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Example/exampleResourceType/myResource"
            },
            "responses": {
              "200": {
                "body": {
                  "value": [
                    {
                      "createdBy": {
                        "deploymentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Resources/deployments/deploymentName",
                        "deploymentTime": "2018-03-09 00:00:00+00:00",
                        "policyDetails": {
                          "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/createdByPolicyAssignment",
                          "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/",
                          "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/createdByPolicyDefinition"
                        }
                      },
                      "lastModifiedBy": {
                        "deploymentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Resources/deployments/deploymentName",
                        "deploymentTime": "2018-04-09 00:00:00+00:00",
                        "policyDetails": {
                          "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/lastModifiedByPolicyAssignment",
                          "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/",
                          "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/lastModifiedByPolicyDefinition"
                        }
                      },
                      "lastUpdateUtc": "2018-08-09 20:40:17.358524+00:00",
                      "policyDetails": {
                        "policyAssignmentDisplayName": "My Policy Assignment 1 Display name",
                        "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/myPolicyAssignment1",
                        "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/",
                        "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/myPolicyDefinition1",
                        "policyDefinitionReferenceId": "123ABC",
                        "policySetDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/providers/Microsoft.Authorization/policySetDefinitions/mySetDefinition"
                      },
                      "trackedResourceId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Example/exampleResourceType/myResource/nestedResourceType/TrackedResource1"
                    },
                    {
                      "lastUpdateUtc": "2018-08-10 00:40:17.358524+00:00",
                      "policyDetails": {
                        "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/providers/Microsoft.Authorization/policyAssignments/myPolicyAssignment2",
                        "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/",
                        "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/myPolicyDefinition2"
                      },
                      "trackedResourceId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Example/exampleResourceType/myResource/nestedResourceType/TrackedResource2"
                    }
                  ]
                }
              }
            }
          },
          "Query at resource scope using query parameters": {
            "parameters": {
              "$filter": "PolicyAssignmentId eq '/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/myPolicyAssignment' AND TrackedResourceId eq '/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Example/exampleResourceType/myResource/nestedResourceType/TrackedResource1'",
              "$top": 1,
              "api-version": "2018-07-01-preview",
              "policyTrackedResourcesResource": "default",
              "resourceId": "subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Example/exampleResourceType/myResource"
            },
            "responses": {
              "200": {
                "body": {
                  "value": [
                    {
                      "createdBy": {
                        "deploymentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Resources/deployments/deploymentName",
                        "deploymentTime": "2018-03-09 00:00:00+00:00",
                        "policyDetails": {
                          "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/createdByPolicyAssignment",
                          "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/",
                          "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/createdByPolicyDefinition"
                        }
                      },
                      "lastModifiedBy": {
                        "deploymentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Resources/deployments/deploymentName",
                        "deploymentTime": "2018-04-09 00:00:00+00:00",
                        "policyDetails": {
                          "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/lastModifiedByPolicyAssignment",
                          "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/",
                          "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/lastModifiedByPolicyDefinition"
                        }
                      },
                      "lastUpdateUtc": "2018-08-09 20:40:17.358524+00:00",
                      "policyDetails": {
                        "policyAssignmentDisplayName": "My Policy Assignment 1 Display name",
                        "policyAssignmentId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyAssignments/myPolicyAssignment1",
                        "policyAssignmentScope": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/",
                        "policyDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Authorization/policyDefinitions/myPolicyDefinition1",
                        "policyDefinitionReferenceId": "123ABC",
                        "policySetDefinitionId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/providers/Microsoft.Authorization/policySetDefinitions/mySetDefinition"
                      },
                      "trackedResourceId": "/subscriptions/fff8dfdb-fff3-fff0-fff4-fffdcbe6b2ef/resourceGroups/myResourceGroup/providers/Microsoft.Example/exampleResourceType/myResource/nestedResourceType/TrackedResource1"
                    }
                  ]
                }
              }
            }
          }
        },
        "x-ms-pageable": {
          "nextLinkName": "nextLink"
        }
      }
    }
  },
  "components": {
    "parameters": {
      "apiVersionParameter": {
        "description": "Client Api Version.",
        "in": "query",
        "name": "api-version",
        "required": true,
        "schema": {
          "type": "string"
        },
        "x-ms-parameter-location": "client"
      },
      "filterParameter": {
        "description": "OData filter expression.",
        "in": "query",
        "name": "$filter",
        "required": false,
        "schema": {
          "type": "string"
        },
        "x-ms-client-name": "Filter",
        "x-ms-parameter-grouping": {
          "name": "QueryOptions"
        },
        "x-ms-parameter-location": "method"
      },
      "managementGroupNameParameter": {
        "description": "Management group name.",
        "in": "path",
        "name": "managementGroupName",
        "required": true,
        "schema": {
          "type": "string"
        },
        "x-ms-parameter-location": "method"
      },
      "managementGroupsNamespaceParameter": {
        "description": "The namespace for Microsoft Management RP; only \"Microsoft.Management\" is allowed.",
        "in": "path",
        "name": "managementGroupsNamespace",
        "required": true,
        "schema": {
          "enum": [
            "Microsoft.Management"
          ],
          "type": "string"
        },
        "x-ms-parameter-location": "method"
      },
      "policyTrackedResourcesResourceParameter": {
        "description": "The name of the virtual resource under PolicyTrackedResources resource type; only \"default\" is allowed.",
        "in": "path",
        "name": "policyTrackedResourcesResource",
        "required": true,
        "schema": {
          "enum": [
            "default"
          ],
          "type": "string"
        },
        "x-ms-parameter-location": "method"
      },
      "resourceGroupNameParameter": {
        "description": "Resource group name.",
        "in": "path",
        "name": "resourceGroupName",
        "required": true,
        "schema": {
          "type": "string"
        },
        "x-ms-parameter-location": "method"
      },
      "resourceIdParameter": {
        "allowReserved": true,
        "description": "Resource ID.",
        "in": "path",
        "name": "resourceId",
        "required": true,
        "schema": {
          "type": "string"
        },
        "x-ms-parameter-location": "method",
        "x-ms-skip-url-encoding": true
      },
      "subscriptionIdParameter": {
        "description": "Microsoft Azure subscription ID.",
        "in": "path",
        "name": "subscriptionId",
        "required": true,
        "schema": {
          "type": "string"
        }
      },
      "topParameter": {
        "description": "Maximum number of records to return.",
        "in": "query",
        "name": "$top",
        "required": false,
        "schema": {
          "format": "int32",
          "minimum": 0,
          "type": "integer"
        },
        "x-ms-client-name": "Top",
        "x-ms-parameter-grouping": {
          "name": "QueryOptions"
        },
        "x-ms-parameter-location": "method"
      }
    },
    "schemas": {
      "PolicyDetails": {
        "description": "The policy details.",
        "properties": {
          "policyAssignmentDisplayName": {
            "description": "The display name of the policy assignment.",
            "readOnly": true,
            "type": "string"
          },
          "policyAssignmentId": {
            "description": "The ID of the policy assignment.",
            "readOnly": true,
            "type": "string"
          },
          "policyAssignmentScope": {
            "description": "The scope of the policy assignment.",
            "readOnly": true,
            "type": "string"
          },
          "policyDefinitionId": {
            "description": "The ID of the policy definition.",
            "readOnly": true,
            "type": "string"
          },
          "policyDefinitionReferenceId": {
            "description": "The policy definition reference ID within the policy set definition.",
            "readOnly": true,
            "type": "string"
          },
          "policySetDefinitionId": {
            "description": "The ID of the policy set definition.",
            "readOnly": true,
            "type": "string"
          }
        },
        "type": "object"
      },
      "PolicyTrackedResource": {
        "description": "Policy tracked resource record.",
        "properties": {
          "createdBy": {
            "$ref": "#/components/schemas/TrackedResourceModificationDetails",
            "description": "The details of the policy triggered deployment that created the tracked resource.",
            "readOnly": true
          },
          "lastModifiedBy": {
            "$ref": "#/components/schemas/TrackedResourceModificationDetails",
            "description": "The details of the policy triggered deployment that modified the tracked resource.",
            "readOnly": true
          },
          "lastUpdateUtc": {
            "description": "Timestamp of the last update to the tracked resource.",
            "format": "date-time",
            "readOnly": true,
            "type": "string"
          },
          "policyDetails": {
            "$ref": "#/components/schemas/PolicyDetails",
            "description": "The details of the policy that require the tracked resource.",
            "readOnly": true
          },
          "trackedResourceId": {
            "description": "The ID of the policy tracked resource.",
            "readOnly": true,
            "type": "string"
          }
        },
        "type": "object"
      },
      "PolicyTrackedResourcesQueryResults": {
        "description": "Query results.",
        "properties": {
          "nextLink": {
            "description": "The URL to get the next set of results.",
            "readOnly": true,
            "type": "string"
          },
          "value": {
            "description": "Query results.",
            "items": {
              "$ref": "#/components/schemas/PolicyTrackedResource"
            },
            "readOnly": true,
            "type": "array"
          }
        },
        "type": "object"
      },
      "QueryFailure": {
        "description": "Error response.",
        "properties": {
          "error": {
            "description": "Error definition.",
            "properties": {
              "code": {
                "description": "Service specific error code which serves as the substatus for the HTTP error code.",
                "readOnly": true,
                "type": "string"
              },
              "message": {
                "description": "Description of the error.",
                "readOnly": true,
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      },
      "TrackedResourceModificationDetails": {
        "description": "The details of the policy triggered deployment that created or modified the tracked resource.",
        "properties": {
          "deploymentId": {
            "description": "The ID of the deployment that created or modified the tracked resource.",
            "readOnly": true,
            "type": "string"
          },
          "deploymentTime": {
            "description": "Timestamp of the deployment that created or modified the tracked resource.",
            "format": "date-time",
            "readOnly": true,
            "type": "string"
          },
          "policyDetails": {
            "$ref": "#/components/schemas/PolicyDetails",
            "description": "The details of the policy that created or modified the tracked resource.",
            "readOnly": true
          }
        },
        "type": "object"
      }
    },
    "securitySchemes": {
      "azure_auth": {
        "description": "Azure Active Directory OAuth2 Flow",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://login.microsoftonline.com/common/oauth2/authorize",
            "scopes": {
              "user_impersonation": "impersonate your user account"
            }
          }
        },
        "type": "oauth2"
      }
    }
  },
  "security": [
    {
      "azure_auth": [
        "user_impersonation"
      ]
    }
  ]
}